spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myjobpartners?serverTimezone=UTC&chyaracterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  messages:
    basename: errors
  mail:
    host: smtp.gmail.com
    port: 587
    username: kyoungsuk3254@gmail.com
    password: cnlgfpagxudlgjzl
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: AKIASZNLEKKPIN2FYW5N
      secretKey: 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
    s3:
      bucket: myjobpartners
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
